# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: "Next.js Bundle Analysis"

on:
  pull_request:
    branches:
      - main # Trigger on PRs to `main` from `dev`
  push:
    branches:
      - dev # Trigger on pushes to `dev`

defaults:
  run:
    working-directory: ./

permissions:
  contents: read # For checking out repository
  actions: read # For fetching base branch bundle stats
  pull-requests: write # For commenting

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Restore next build cache
        uses: actions/cache@v3
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build next.js app
        run: ./node_modules/.bin/next build

      # On `dev` branch, upload the analysis artifact
      - name: Upload bundle analysis artifact
        if: github.ref_name == 'dev'
        uses: actions/upload-artifact@v3
        with:
          name: bundle-analysis
          path: .next/analyze/__bundle_analysis.json

      # On PR to `main`, download the `dev` artifact for comparison
      - name: Download dev branch bundle stats
        if: github.event_name == 'pull_request'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Next.js Bundle Analysis # Workflow name on the `dev` branch
          name: bundle-analysis # Name of the artifact
          branch: dev # Reference `dev` as the source branch
          path: .next/analyze/base

      # Ensure the analyze directory exists for safety
      - name: Create Analyze Directory
        run: mkdir -p .next/analyze/base

      # Verify if the dev artifact is downloaded (exit if not found)
      - name: Verify Downloaded Dev Artifacts
        if: github.event_name == 'pull_request'
        run: |
          echo "Checking for dev base directory..."
          ls -laR .next/analyze/base || (echo "Dev base directory does not exist. Exiting..." && exit 1)

      # Compare the dev bundle with the current main branch bundle
      - name: Compare with Base Branch Bundle
        if: github.event_name == 'pull_request'
        run: npx -p nextjs-bundle-analysis compare

      # Debugging step to check contents of the analyze directory
      - name: Debug Download Artifact
        if: github.event_name == 'pull_request'
        run: |
          echo "Contents of .next/analyze directory:"
          ls -la .next/analyze || echo "Analyze directory does not exist."

      # Post the analysis results as a comment on the PR
      - name: Get Comment Body
        id: get-comment-body
        if: github.event_name == 'pull_request'
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "<!-- __NEXTJS_BUNDLE -->"

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
